name: 🐞 Bug Report
description: Create a report to help us improve CrossMacro
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Linux (X11)
        - Hyprland (Wayland)
        - KDE Plasma (Wayland)
        - GNOME (Wayland)
        - Other Wayland
        - Windows
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: e.g., Arch Linux, Ubuntu 24.04, Fedora 40, NixOS, Windows 11
      placeholder: Arch Linux / NixOS / Windows 11
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: When I press F8 to record...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant logs.
      render: shell

